apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
      - name: users
        image: djebby/kub-users:latest
        env:
          - name: AUTH_ADDRESS
            # value: "10.101.119.33"
            value: "auth-service.default"
